# 1234 替换子串得到平衡字符串
# from typing import *
from collections import *


# leetcode submit region begin(Prohibit modification and deletion)
class Solution:
    def balancedString(self, s: str) -> int:
        n = len(s)
        ans = n
        left = 0
        cnt = Counter(s)
        # { 数量比 n/4 多的字符 : 多出的额数量 }
        # 移动 right 遇到在 more 的 c more[c] -= 1
        # more[c] 都 <= 0 了，说明区间内有足够原本多的的字符可以替换使得整个字符串平衡，这是个可以替换的区间
        more = {k: v - n // 4 for k, v in cnt.items() if v > n // 4}
        if sum(more.values()) == 0:  # 没有字符比 n/4 多，已经是平衡字符串
            return 0
        for right, c in enumerate(s):
            if c in more:
                more[c] -= 1
            while left <= right and max(more.values()) <= 0:  # all(v <= 0 for v in more.values()) :
                ans = min(ans, right - left + 1)
                if s[left] in more:
                    more[s[left]] += 1
                left += 1
        return ans


# leetcode submit region end(Prohibit modification and deletion)
"""
"WQWRQQQW"
"QEQRWRRWWWRQQQWQQEQEQREWRQEQRQQRRQEW"
"EQWEEEWERRWERQQQWWQEQWEEWQRWQWWWQWRWEWERWQEWWQWWQRRQWQERWWQRERRRRRWQEQRERRWRREEEERRWERQRQEWREQREWWEWRRRERWRRWEQWQQRRWQEREEEERWQWEWQEWRWREWQEREQWQEQWRQQQWRWWRWERWQWWQQREWREEWRWWQRWQRWWQWWREWWWEWQRWRRWQEWRRRWWQRRQREQRWRRQWREQWEQRWQRWQRWERRREEREEQQEREREWQQWRWEWEQQRWEWEQWEEQEEERWWWEQRRRWRQWWQQEQRWRWRWEQRRQRQRQWWWEQWERWEQRWQRERWQQQWWWQWRWEREWRQWQWERRQQWRQWRWQQQEEQREQWRWWEQRWWWEEERQWQWEWRQQRWQWEQQEWEWRQWWERERQREWWEEREQRRWQRRRWQEEWEWQEEEQRQQEWREQWQWRRWREQQQEEEWWRQEEEWQQEQEQWWREEWRQQQRQQEERQQQEEQWERRQEEQQRQQQWWEQEEQWRQWEQWEEQQEEQQEERQEEWQEEEWQRERRERQRQQQQWRQRRQQWQEEWRRQEWQWREWERWQRQQWEEERREQEEQWQQRWERWRWEEQWEREREWRWREEWRRRQEQQERRRERQRQWRWWREQQWWEQQWQWRRWEQRWEQQEQWWWQWWEWWEEEWEWRQWQWWQQQQEWRQEQWWRWWEQRRRWREREWRQQERQRQEQWWQQWRQRRQRWRQEEEWRRQREWRRERRQEEREERWEQQQWEWWEERWQWQQWWEQWWQWERRRWQWEEEEQEEWQRRWRWEEEWEWRREWWEQQERRQWQEWQQQRWEWRQEQWREWEWEEWWWWWWWWEQRWRRQQEEEERQEWQQEQQEEEWWRWRQQQQWRREEWRWWWQRWRWRWQWWEREQQEEEWREERQEWEERQWQREEQRQWEQEREQWWEWEEWREREWRQQWREEEEQRRWRWRQRRRWRQQQRRQQRQEWEEQQEREWQEEWEWWEQRRQWRQRQQREREQRWWQEEERREWRREWRRRQQQRQEQEWQWEEQQERQRRRWRRWWEEQRWQQQQQQWREWEWWRQREWREQRRQEQEERRQERWEEQRWWQRWQRWWERQEWEQERWRWQRQEEQEQEWWQWWRREEWEWWRRQEQQWEERWEWWWQEWWRRWRWQEERQRQWEQQEWWRRRRWQEWQQQQWWEEE"
"""
t = "WQWRQQQW"
s = Solution()
print(s.balancedString(t))
